# Jekyll Configuration
title: "EuroTAP | Europe's First Quantum-Safe Payment Revolution"
description: "Revolutionizing digital payments with post-quantum ML-DSA-65 technology"
baseurl: ""
url: "https://eurotap.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-primer

# Exclude files
exclude:
  - README.md
  - FORCE_UPDATE_*.txt
  - "*.backup"
  - node_modules/
  - vendor/

# Include files
include:
  - demos/

# Jekyll plugins
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag

# GitHub Pages settings
repository: EuroTap/Eurotap-quantum-nexus
